_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
architecture:
    value: vgg19
dataset:
    value: TauKO
epochs:
    value: 1
learning_rate:
    value: 1e-05
